package com.singraul.app.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

	
	// default user name is : user
	// password will be generated by server :
	@GetMapping("/helloSecurity")
	public String hello() {
		return "Hello Spring Basic Security Application";
	}
	
}
